### ISSUE TITLE
Not able to void a data or individual on data entry appp

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1128]
**Describe the bug**
Not able to void a data or individual on data entry app
This is happening on production env also

showing while voiding this subject

org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670) at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:765) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:750)

**To Reproduce**

1. Login any orgnisation
2. Click on search 
3. click on any individual 
4. try to void it
5. see the error

**Expected behavior**
user should able to void the individual 
![void](https://github.com/avniproject/avni-webapp/assets/104890488/f9d8a590-1dc6-4869-b0ac-e24a9dcc519a)

**Comment by mahalakshme** [comment]
@AchalaBelokar can u mention org details and the individual details? I am unable to reproduce the issue.

**Comment by AchalaBelokar** [comment]
- [ ] Ach@sakhiapp individual  A B just try to avoid it
