### ISSUE TITLE
Not able to edit the image on webapp

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1308]
### Describe the bug
Not able to edit(clicking on cross-delete icon) the image on webapp web app is breaking while doing this
Login with AchalaB@rwbitiuat 
and search any work order then edit and then click on cancel the image 

this error is comming

### Message
this.getValueWrapper(...).toggleAnswer is not a function

Error Stack
TypeError: this.getValueWrapper(...).toggleAnswer is not a function
at n.value (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:1183683)
at e.value (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:1441199)
at e.value (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:1444323)
at Object.updateObservations (https://prerelease.avniproject.org/static/js/main.12e64479.chunk.js:1:38847)
at Object.updateObservations (https://prerelease.avniproject.org/static/js/main.12e64479.chunk.js:1:1128619)
at https://prerelease.avniproject.org/static/js/main.12e64479.chunk.js:1:977758
at D (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:4192829)
at Generator._invoke (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:4192617)
at e.<computed> [as next] (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:4193008)
at A (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:2067566)

Saga Stack
at Nu
at Ji
at kt
at St
at l
at Ct
TypeError: this.getValueWrapper(...).toggleAnswer is not a function
at n.value (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:1183683)
at e.value (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:1441199)
at e.value (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:1444323)
at Object.updateObservations (https://prerelease.avniproject.org/static/js/main.12e64479.chunk.js:1:38847)
at Object.updateObservations (https://prerelease.avniproject.org/static/js/main.12e64479.chunk.js:1:1128619)
at https://prerelease.avniproject.org/static/js/main.12e64479.chunk.js:1:977758
at D (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:4192829)
at Generator._invoke (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:4192617)
at e.<computed> [as next] (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:4193008)
at A (https://prerelease.avniproject.org/static/js/2.cd1709e8.chunk.js:1:2067566)

**To Reproduce**

1. Login with rwbnitiuat
2. Search  a work order 003 
3. click on edit the work order
4. and then cancel the image which  is present 
5. See error

**Expected behavior**
user is able to cancel the image\

**Screenshots**

https://github.com/user-attachments/assets/b34a4134-3d02-4537-901e-09bcd3d789af

in your problem.

**Analysis**
Issue present in prod as well

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by 1t5j0y** [comment]
Unable to simulate with multi select element. Looks like a case of form element changed from single select to multi select.
No fix.
