### ISSUE TITLE
[DEA] General encounters page not rendering

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1378]
https://avni.freshdesk.com/a/tickets/4941

### Steps to reproduce:
- org: CTRITH_IPH, env: prod

- Login in via webapp 
- Search with Jad3419 or Jad3420 in the field 'Individual ID'
- Go to General tab
- The app shows error page with below stacktrace 
```
Message
Cannot read properties of null (reading 'uuid')

Error Stack
TypeError: Cannot read properties of null (reading 'uuid')
at Mc (https://app.avniproject.org/static/js/main.d1b3d91d.chunk.js:1:185341)
at Ji (https://app.avniproject.org/static/js/2.9cc0dbb3.chunk.js:1:4074617)
at Fa (https://app.avniproject.org/static/js/2.9cc0dbb3.chunk.js:1:4083505)
at bs (https://app.avniproject.org/static/js/2.9cc0dbb3.chunk.js:1:4122366)
```

### AC:
The error message should be meaningful or if it is some case not handled, should get handled. Comment regarding the same in this card.

**Comment by mahalakshme** [comment]
- Not handled for program encounter for similar case(it is ProgramEncounterMapper file) - not sure how I can mention the AC in these cases, since I was not sure about the root cause. After identifying the root-cause such cards can be moved back to Analysis as well.
