### ISSUE TITLE
Users created from csv uploads are unable to login

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#823]
We have created new set of users for APF, but then these users are facing issue with login --

 **org.avni.web.ErrorInterceptors           : null

java.lang.NullPointerException: null
	at org.avni.web.request.syncAttribute.UserSyncSettings.fromUserSyncSettings(UserSyncSettings.java:61)
	at org.avni.web.UserController.getUser(UserController.java:123)
	at org.avni.web.UserController$$FastClassBySpringCGLIB$$6c21b0b5.invoke(<generated>)**

To resolve the above issue , using the following script as work around.
set role apfodishauat;
update users
set sync_settings           = '{}',
    last_modified_by_id     = (select id from users where username = 'nupoork@apfodishauat'),
    last_modified_date_time = now()
where sync_settings is null;

**Comment by petmongrels** [comment]
Empty sync settings '{}' will be created.
