### ISSUE TITLE
Unable to save Calcutta Registration form

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#896]
**Steps to reproduce:**

Login to calcutta kids of prerelease -> Click on edit of Calcutta kids registration form -> Click on save -> show error that states "Server error received Unable to commit against JDBC Connection; nested exception is org.hibernate.TransactionException: Unable to commit against JDBC Connection"

**Server error log:**
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "form_element_form_element_group_id_display_order_organisati_key"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.executeTransactionCommand(AbstractJdbc2Connection.java:791)

**Findings:**
- tried the below query in prod and was unable to find any duplicate rows.
```
SELECT form_element_group_id,
        display_order
FROM form_element where organisation_id=19
GROUP BY form_element_group_id, display_order
HAVING COUNT(form_element_group_id) >1;

```
- Checked the request payload, the display order of each form element within a group was unique.
- The constraint has been added in this file: V1_23__AddOrganisationIdToFormElementDisplayOrderUniqueConstraint.sql

**Comment by AchalaBelokar** [comment]
It is happen with RWB Niti uat unable to edit or add the questions in the form

 ![Screenshot 2023-02-09 at 8.47.20 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/e38bb5e5-05b4-4f49-b520-a20d3f575eeb)

**Comment by himeshr** [comment]
This involves replacing constraints that are present on display_order uniqueness in Form_Element and Form_element_group. This change takes a long time and hence the prod deploy would need to be done at night.

**Comment by himeshr** [comment]
Code changes have been deployed to pre-release environment and can only be tested there.
