### ISSUE TITLE
Longitudinal export failing for Household subject type

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#951]
For RAHI implementation on production, getting following error while downloading Household data --

java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at org.avni.server.exporter.ExportCSVFieldExtractor.lambda$getObs$6(ExportCSVFieldExtractor.java:374)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

**Comment by vinayvenu** [comment]
@nupoorkhandelwal can you provide Freshdesk link here?

**Comment by petmongrels** [comment]
@nupoorkhandelwal there are number of issues possible in this export. can you share the json that you submitted.
