### ISSUE TITLE
Unable to open app designer for some organisation( messagesToGlific, LAHI) staging 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#952]
/web/subjectType is failing for a bunch of orgs on staging (messagesToGlific, LAHI) which is preventing app designer from loading
Error: query did not return a unique result: 9;nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 9

...
	at org.avni.server.service.FormMappingService.find(FormMappingService.java:238)
...
	at org.avni.server.web.SubjectTypeController.getAll(SubjectTypeController.java:85)

**Comment by AchalaBelokar** [comment]
closed.. there is another card created for this.
